var waveObj=function(){
	this.x=[];
	this.y=[];
	this.alive=[];
	this.r=[];
	this.num;//备用圈圈数
	this.maxR=[];
	this.color=[];//圈圈颜色
	this.alpha;
}
waveObj.prototype.init=function(){
		this.num=5;
		this.alpha=1;
		for(var i=0;i<this.num;i++){
			this.x[i]=0;
			this.y[i]=0;
			this.r[i]=10;
			this.alive[i]=false;
			this.maxR[i]=40;
			this.color[i]="255,255,255";
		}
}
waveObj.prototype.drawCircle=function(){
	for(var i=0;i<20;i++){
		if(this.alive[i]){
			this.r[i]+=deltaTime*0.05;
			if(this.r[i]>this.maxR[i]){
				this.r[i]=0;
				this.alive[i]=false;
			}
			this.alpha=1-this.r[i]/this.maxR[i];
			ctx2.save();
			ctx2.beginPath();
			ctx2.arc(this.x[i],this.y[i],this.r[i],0*Math.PI,2*Math.PI);
			ctx2.strokeStyle="rgba("+this.color[i]+","+this.alpha+")";
			ctx2.shadowBlur=3;
			ctx2.shadowColor="rgb("+this.color[i]+")";
			ctx2.lineWidth=3;
			ctx2.stroke();
			ctx2.restore();
		}
	}
}
waveObj.prototype.born=function(x,y,type){
	for(var i=0;i<20;i++){
			if(!this.alive[i]){
				this.x[i]=x;
				this.y[i]=y;
				if(type){
					wave.maxR[i]=30;
					wave.color[i]="255,255,255";
				}else{
					this.maxR[i]=100;
					this.color[i]="255,125,0";
				}
				this.alive[i]=true;
				break;
			}
		}
}
